# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zero Kelvin
tagline: 'Gaining Energy'
email: kelvincoding2@gmail.com
description: 'Gaining Energy to Move Forward'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.kelvincoding.com" # the base hostname & protocol for your site
twitter_username: kelvincoding
github_username:  kelvincoding
paginate: 5

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
permalink: pretty