# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Zero Kelvin
tagline:             'Gaining Energy'
description:         'A Blog on learning to move forward in life'
url:                 http://blog.kelvincoding.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Kelvin Rodriguez
  # url:               https://twitter.com/mdo
  email:             kelvincoding2@gmail.com

# Custom vars
version:             1.0.0
gems: [jekyll-paginate]
